Repository storybookjs/bench, pull requests merged in 2022-11, with the labels that each got.

#12 upgrades and add a handling for storybook7 which has no main.js for the manager
  .github/workflows/main.yml
  README.md
  package.json
  src/buildBrowseStorybook.ts
  src/helpers/format.ts
  src/helpers/static.ts
  src/helpers/timing.ts
  src/index.ts
  src/installAddonBench.ts
  src/startStorybook.ts
  src/upload.ts
  tsconfig.json
  yarn.lock
Labels: major

#13 Fix handling of millisecond startup time
  src/startStorybook.ts
  test/buildBrowseStorybook.test.ts
Labels: bug, patch

#14 Fix support for main.cjs
  src/installAddonBench.ts
Labels: bug

#16 Fix triple-counting manager size
  src/buildBrowseStorybook.ts
Labels: bug

#17 Use next version of addon-bench
  src/installAddonBench.ts
Labels: enhancement
